config/routes.rb
Projectar::Application.routes.draw do
  resources :people

  resources :households

  resources :sides
  
  match '/csv_import' => 'csv_import#csv_import'
  match '/csv_import/house_hold_summary' => 'csv_import#house_hold_summary'

end

app/models/side.rb
class Side < ActiveRecord::Base
  has_many :households, :dependent => :destroy
  
  validates_uniqueness_of :name
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  # GET /sides
  # GET /sides.xml
  def index
    @sides = Side.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sides }
    end
  end

  # GET /sides/1
  # GET /sides/1.xml
  def show
    @side = Side.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @side }
    end
  end

  # GET /sides/new
  # GET /sides/new.xml
  def new
    @side = Side.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @side }
    end
  end

  # GET /sides/1/edit
  def edit
    @side = Side.find(params[:id])
  end

  # POST /sides
  # POST /sides.xml
  def create
    @side = Side.new(params[:side])

    respond_to do |format|
      if @side.save
        format.html { redirect_to(@side, :notice => 'Side was successfully created.') }
        format.xml  { render :xml => @side, :status => :created, :location => @side }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @side.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sides/1
  # PUT /sides/1.xml
  def update
    @side = Side.find(params[:id])

    respond_to do |format|
      if @side.update_attributes(params[:side])
        format.html { redirect_to(@side, :notice => 'Side was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @side.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sides/1
  # DELETE /sides/1.xml
  def destroy
    @side = Side.find(params[:id])
    @side.destroy

    respond_to do |format|
      format.html { redirect_to(sides_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sides_helper.rb
module SidesHelper
end

app/views/sides/_form.html.erb
<%= form_for(@side) do |f| %>
  <% if @side.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@side.errors.count, "error") %> prohibited this side from being saved:</h2>

      <ul>
      <% @side.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sides/edit.html.erb
<h1>Editing side</h1>

<%= render 'form' %>

<%= link_to 'Show', @side %> |
<%= link_to 'Back', sides_path %>

app/views/sides/index.html.erb
<h1>Listing sides</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sides.each do |side| %>
  <tr>
    <td><%= side.name %></td>
    <td><%= link_to 'Show', side %></td>
    <td><%= link_to 'Edit', edit_side_path(side) %></td>
    <td><%= link_to 'Destroy', side, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Side', new_side_path %>

app/views/sides/new.html.erb
<h1>New side</h1>

<%= render 'form' %>

<%= link_to 'Back', sides_path %>

app/views/sides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @side.name %>
</p>


<%= link_to 'Edit', edit_side_path(@side) %> |
<%= link_to 'Back', sides_path %>