config/routes.rb
Projectar::Application.routes.draw do
  resources :people

  resources :households

  resources :sides
  
  match '/csv_import' => 'csv_import#csv_import'
  match '/csv_import/house_hold_summary' => 'csv_import#house_hold_summary'

end

app/models/household.rb
class Household < ActiveRecord::Base
  belongs_to :side
  has_many :persons
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # GET /households
  # GET /households.xml
  def index
    @households = Household.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @households }
    end
  end

  # GET /households/1
  # GET /households/1.xml
  def show
    @household = Household.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @household }
    end
  end

  # GET /households/new
  # GET /households/new.xml
  def new
    @household = Household.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.xml
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to(@household, :notice => 'Household was successfully created.') }
        format.xml  { render :xml => @household, :status => :created, :location => @household }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @household.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.xml
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to(@household, :notice => 'Household was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @household.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.xml
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to(households_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/_form.html.erb
<%= form_for(@household) do |f| %>
  <% if @household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/households/edit.html.erb
<h1>Editing household</h1>

<%= render 'form' %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<h1>Listing households</h1>

<table>
  <tr>
	<th>Name</th>
	<th>Side</th>
    <th>Password</th>
    <th>Email</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @households.each do |household| %>
  <tr>
	<td><%= household.name %></td>
	<td><%= get_household_side(household)%>
    <td><%= household.password %></td>
    <td><%= household.email %></td>
    <td><%= household.notes %></td>
    <td><%= link_to 'Show', household %></td>
    <td><%= link_to 'Edit', edit_household_path(household) %></td>
    <td><%= link_to 'Destroy', household, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Household', new_household_path %>

app/views/households/new.html.erb
<h1>New household</h1>

<%= render 'form' %>

<%= link_to 'Back', households_path %>

app/views/households/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Password:</b>
  <%= @household.password %>
</p>

<p>
  <b>Email:</b>
  <%= @household.email %>
</p>

<p>
  <b>Notes:</b>
  <%= @household.notes %>
</p>


<%= link_to 'Edit', edit_household_path(@household) %> |
<%= link_to 'Back', households_path %>